# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    parameters:
      login-has-changes:
        type: string
        default: ''
      main-has-changes:
        type: string
        default: ''
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo npm i -g lerna
      - run: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
            - packages/login/node_modules
            - packages/main/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - when:
          condition: << parameters.login-has-changes >>
          steps:
            - run: cd packages/login && yarn test

      - when:
          condition: << parameters.main-has-changes >>
          steps:
            - run: cd packages/main && yarn test

workflows:
  build-test-deploy:
    jobs:
      - build:
          login-has-changes: $(git log master..test --format=format:%H --full-diff packages/login)
          main-has-changes: $(git log master..test --format=format:%H --full-diff packages/main)
